# Generated by Django 2.2.15 on 2020-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_lokation_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=256)),
            ],
        ),
    ]
