# Generated by Django 2.2.15 on 2020-08-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storez_inventory', to='home.Inventory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storez_location', to='home.Lokation')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storez_name', to='home.Name')),
            ],
        ),
    ]
